### ISSUE TITLE
distribute_setup.py doesn't work properly

### ISSUE THREAD

**Issue by mpounsett** [bortzmeyer/dns-lg#42]
Your ```distribute_setup.py``` module fails to retrieve whatever it's trying to download and blocks building the package.  Simply removing references to it from ```setup.py``` fixes the problem.

```
% python setup.py build
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.16.tar.gz
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    use_setuptools()
  File "/home/matt/src/dns-lg/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/matt/src/dns-lg/distribute_setup.py", line 124, in _do_download
    to_dir, download_delay)
  File "/home/matt/src/dns-lg/distribute_setup.py", line 193, in download_setuptools
    src = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required
```

**Comment by mpounsett** [comment]
Suggested fix:

``` diff
% git diff setup.py
diff --git a/setup.py b/setup.py
index dd165c5..ec167a7 100644
--- a/setup.py
+++ b/setup.py
@@ -1,8 +1,5 @@
 #!/usr/bin/env python

-# distribute
-from distribute_setup import use_setuptools
-use_setuptools()
 from setuptools import setup

 setup(name='DNS-LG',```

**Comment by bortzmeyer** [comment]
Python packaging is really a mess :-( I cannot really remove that, it is necessary to get the correct distribute package.

But, in this case, it was much simpler "HTTP Error 403: SSL is required" I changed the URL of PyPi to use HTTPS, it should work now.

**Comment by mpounsett** [comment]
We can discuss Python packaging another time.. pipy works really well.  But as far as I can tell, the `distribute` package isn't actually required.  I simply removed it and the build worked fine.
